---

- name: Echo
  hosts: frontEndServers
  tasks:
  
    - name: Print text
      debug:
        msg: "{{text}}"
    - name: Create directory
    file:
      path: /tmp/KRONBERGA/java_dns/
      state: directory    
